# Generated by Django 5.2.1 on 2025-06-10 15:52

import django.core.validators
import django.db.models.deletion
import resumes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Only PDF files are allowed', upload_to=resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Analysis Completed'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('job_titles', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('work_experience', models.JSONField(blank=True, default=list)),
                ('analysis_summary', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
