# Generated by Django 5.2.1 on 2025-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='error_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_extraction_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='warning_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Analysis Completed'), ('completed_with_warnings', 'Completed with Warnings'), ('failed', 'Analysis Failed')], default='pending', max_length=30),
        ),
    ]
