services:
  - type: web
    name: smart-resume-matcher
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd smart_resume_matcher
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd smart_resume_matcher && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    disk:
      name: smart-resume-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONPATH
        value: "/opt/render/project/src/smart_resume_matcher"
      - key: DATABASE_URL
        value: "sqlite:////var/data/db.sqlite3"
