services:
  - type: web
    name: smart-resume-matcher
    env: python
    buildCommand: ./render_deploy.sh
    startCommand: ./start.sh
    disk:
      name: smart-resume-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONPATH
        value: "/opt/render/project/src/smart_resume_matcher"
      - key: DATABASE_URL
        value: "sqlite:////var/data/db.sqlite3"
