services:
  - type: web
    name: smart-resume-matcher
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    disk:
      name: smart-resume-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".render.com"
      - key: REDIS_URL
        fromService:
          name: smart-resume-redis
          type: redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: worker
    name: smart-resume-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: REDIS_URL
        fromService:
          name: smart-resume-redis
          type: redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
  
  - type: worker
    name: smart-resume-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config beat --loglevel=info
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: REDIS_URL
        fromService:
          name: smart-resume-redis
          type: redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: redis
    name: smart-resume-redis
    plan: free
    maxmemoryPolicy: volatile-lru
