# Generated by Django 5.2.1 on 2025-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
