# Generated by Django 5.2.1 on 2025-06-17 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_requirements_alter_job_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hh_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
