# Generated by Django 5.2.1 on 2025-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_hh_url_alter_job_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='analysis_version',
            field=models.CharField(blank=True, default='v1', max_length=50),
        ),
    ]
