# Generated by Django 5.2.1 on 2025-06-10 17:01

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=accounts.fields.SafeImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
